/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.PreparedStatement;
import controller.ClientController;
import controller.ServerController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import model.Database;
import model.PeminjamanRuang;
import model.User;
import model.ChatClient;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.ChatClient;

/**
 *
 * @author TITHA
 */

public class DashbordUser extends javax.swing.JFrame {
    
    private String idUser;
    /**
     * Creates new form DashbordUser
     */
    public DashbordUser(String idUser) {
        initComponents();
        this.idUser=idUser;
        loadTableData();
        tampil_ruang();
        
        peminjamanTable.getColumnModel().getColumn(0).setPreferredWidth(70);
        peminjamanTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        peminjamanTable.getColumnModel().getColumn(2).setPreferredWidth(115);
        peminjamanTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        peminjamanTable.getColumnModel().getColumn(4).setPreferredWidth(75);
        peminjamanTable.getColumnModel().getColumn(5).setPreferredWidth(80);
        
        editTable.getColumnModel().getColumn(0).setPreferredWidth(70);
        editTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        editTable.getColumnModel().getColumn(2).setPreferredWidth(115);
        editTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        editTable.getColumnModel().getColumn(4).setPreferredWidth(75);
        editTable.getColumnModel().getColumn(5).setPreferredWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menuBuat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menuEdit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menuCS = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menuLogout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        layarUtama = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        peminjamanTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        cariTextField1 = new javax.swing.JTextField();
        buatPeminjaman = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        penggunaTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        kegiatanTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tanggalChooser = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        daftarRuang = new javax.swing.JComboBox<>();
        pinjamButton = new javax.swing.JButton();
        errorPengguna = new javax.swing.JLabel();
        errorKegiatan = new javax.swing.JLabel();
        errorTanggal = new javax.swing.JLabel();
        errorRuang = new javax.swing.JLabel();
        editPeminjaman = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        editTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        tanggalEdit = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        ruangEdit = new javax.swing.JComboBox<>();
        idPmjmEdit = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        cariTextField2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        CS = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cboConnection = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listMessege = new javax.swing.JList<>();
        txtMessege = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 211, 94));

        menu.setBackground(new java.awt.Color(13, 59, 102));
        menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 0), new java.awt.Color(51, 0, 0), new java.awt.Color(51, 0, 0), new java.awt.Color(51, 0, 0)));
        menu.setPreferredSize(new java.awt.Dimension(185, 284));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 240, 202));
        jLabel2.setText("MENU");

        menuHome.setBackground(new java.awt.Color(13, 59, 102));
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuHomeMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 240, 202));
        jLabel3.setText("Home");

        javax.swing.GroupLayout menuHomeLayout = new javax.swing.GroupLayout(menuHome);
        menuHome.setLayout(menuHomeLayout);
        menuHomeLayout.setHorizontalGroup(
            menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuHomeLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuHomeLayout.setVerticalGroup(
            menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(43, 43, 43))
        );

        menuBuat.setBackground(new java.awt.Color(13, 59, 102));
        menuBuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuBuatMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 240, 202));
        jLabel4.setText(" Buat Peminjaman ");

        javax.swing.GroupLayout menuBuatLayout = new javax.swing.GroupLayout(menuBuat);
        menuBuat.setLayout(menuBuatLayout);
        menuBuatLayout.setHorizontalGroup(
            menuBuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBuatLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(27, 27, 27))
        );
        menuBuatLayout.setVerticalGroup(
            menuBuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBuatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        menuEdit.setBackground(new java.awt.Color(13, 59, 102));
        menuEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuEditMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 240, 202));
        jLabel5.setText("Ubah Peminjaman ");

        javax.swing.GroupLayout menuEditLayout = new javax.swing.GroupLayout(menuEdit);
        menuEdit.setLayout(menuEditLayout);
        menuEditLayout.setHorizontalGroup(
            menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuEditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(25, 25, 25))
        );
        menuEditLayout.setVerticalGroup(
            menuEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuEditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        menuCS.setBackground(new java.awt.Color(13, 59, 102));
        menuCS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuCSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuCSMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 240, 202));
        jLabel6.setText("Customer Services");

        javax.swing.GroupLayout menuCSLayout = new javax.swing.GroupLayout(menuCS);
        menuCS.setLayout(menuCSLayout);
        menuCSLayout.setHorizontalGroup(
            menuCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuCSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(23, 23, 23))
        );
        menuCSLayout.setVerticalGroup(
            menuCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuCSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuLogout.setBackground(new java.awt.Color(13, 59, 102));
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(250, 240, 202));
        jLabel7.setText(" Logout ");

        javax.swing.GroupLayout menuLogoutLayout = new javax.swing.GroupLayout(menuLogout);
        menuLogout.setLayout(menuLogoutLayout);
        menuLogoutLayout.setHorizontalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLogoutLayout.setVerticalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuCS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(menuHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuBuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layarUtama.setBackground(new java.awt.Color(255, 234, 167));
        layarUtama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 0), new java.awt.Color(51, 0, 0), new java.awt.Color(51, 0, 0), new java.awt.Color(51, 0, 0)));
        layarUtama.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(13, 59, 102));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 240, 202));
        jLabel8.setText("Selamat Datang");

        peminjamanTable.setAutoCreateRowSorter(true);
        peminjamanTable.setBackground(new java.awt.Color(250, 240, 202));
        peminjamanTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 0), new java.awt.Color(51, 0, 0), new java.awt.Color(51, 51, 0), new java.awt.Color(51, 0, 0)));
        peminjamanTable.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        peminjamanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Peminjaman", "Pengguna", "Kegiatan", "Ruang", "Tanggal", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        peminjamanTable.setRowHeight(30);
        peminjamanTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(peminjamanTable);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 240, 202));
        jLabel9.setText("Daftar Peminjaman Ruang");

        jPanel2.setBackground(new java.awt.Color(254, 249, 210));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0), new java.awt.Color(204, 102, 0)));

        jLabel19.setBackground(java.awt.Color.orange);
        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(13, 59, 102));
        jLabel19.setText("Tata cara penggunaan:");

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(13, 59, 102));
        jLabel20.setText("1) Silahkan tekan menu buat peminjaman untuk membuat pengajuan peminjaman ruang. ");

        jLabel33.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(13, 59, 102));
        jLabel33.setText("melakukan perubahan atau pengajuan mengalami penolakan.");

        jLabel34.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(13, 59, 102));
        jLabel34.setText("2) Silahkan tekan menu ubah peminjaman untuk mengubah pengajuan peminjaman apabila ingin");

        jLabel35.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(13, 59, 102));
        jLabel35.setText("3) Pengajuan peminjaman yang berhasil dibuat akan tampil di tabel di bawah.");

        jLabel36.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(13, 59, 102));
        jLabel36.setText("4) Jika memiliki kendala, tekan menu Customer Services untuk mendapatkan saran.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(250, 240, 202));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        jPanel8.setAlignmentX(0.0F);
        jPanel8.setAlignmentY(0.0F);

        jLabel38.setBackground(new java.awt.Color(255, 0, 153));
        jLabel38.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel38))
        );

        cariTextField1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        cariTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(homeLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cariTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cariTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layarUtama.add(home, "card2");

        buatPeminjaman.setBackground(new java.awt.Color(13, 59, 102));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(250, 240, 202));
        jLabel10.setText("FORM PEMINJAMAN");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(250, 240, 202));
        jLabel14.setText("Pengguna");

        penggunaTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        penggunaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaTextFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(250, 240, 202));
        jLabel13.setText("Kegiatan");

        kegiatanTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(250, 240, 202));
        jLabel11.setText("Tanggal");

        tanggalChooser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(250, 240, 202));
        jLabel15.setText("Ruang");

        daftarRuang.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        daftarRuang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "321", "322", "323", "324", "325", "326", "327", "328", "331", "332", "333", "334", "335", "336", "337", "338", "341", "342", "343", "344", "345", "346", "347", "348", "241", "242", "243", "251", "252", "253", "254", "255", "256", "257", "261", "262", "263", "264", "265", "266", "267", "Auditorium", "Basement" }));

        pinjamButton.setBackground(new java.awt.Color(250, 240, 202));
        pinjamButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        pinjamButton.setForeground(new java.awt.Color(13, 59, 102));
        pinjamButton.setText("Pinjam");
        pinjamButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        pinjamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamButtonActionPerformed(evt);
            }
        });

        errorPengguna.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N

        errorKegiatan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N

        errorTanggal.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N

        errorRuang.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N

        javax.swing.GroupLayout buatPeminjamanLayout = new javax.swing.GroupLayout(buatPeminjaman);
        buatPeminjaman.setLayout(buatPeminjamanLayout);
        buatPeminjamanLayout.setHorizontalGroup(
            buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buatPeminjamanLayout.createSequentialGroup()
                .addGroup(buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(buatPeminjamanLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pinjamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buatPeminjamanLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(buatPeminjamanLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(daftarRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buatPeminjamanLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tanggalChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buatPeminjamanLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kegiatanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buatPeminjamanLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(penggunaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorKegiatan, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(errorPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(errorRuang, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(errorTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(buatPeminjamanLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buatPeminjamanLayout.setVerticalGroup(
            buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buatPeminjamanLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel10)
                .addGap(36, 36, 36)
                .addGroup(buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buatPeminjamanLayout.createSequentialGroup()
                        .addGroup(buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(penggunaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kegiatanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(buatPeminjamanLayout.createSequentialGroup()
                        .addComponent(errorPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(errorKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(buatPeminjamanLayout.createSequentialGroup()
                        .addComponent(errorTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(errorRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buatPeminjamanLayout.createSequentialGroup()
                        .addGroup(buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(daftarRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addComponent(pinjamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        layarUtama.add(buatPeminjaman, "card3");

        editPeminjaman.setBackground(new java.awt.Color(13, 59, 102));
        editPeminjaman.setForeground(new java.awt.Color(13, 59, 102));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(250, 240, 202));
        jLabel12.setText("UBAH PEMINJAMAN");

        editTable.setAutoCreateRowSorter(true);
        editTable.setBackground(new java.awt.Color(255, 255, 204));
        editTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 0), new java.awt.Color(51, 0, 0), new java.awt.Color(51, 51, 0), new java.awt.Color(51, 0, 0)));
        editTable.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        editTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Peminjaman", "Pengguna", "Kegiatan", "Ruang", "Tanggal", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        editTable.setRowHeight(30);
        editTable.getTableHeader().setReorderingAllowed(false);
        editTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(editTable);

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(250, 240, 202));
        jLabel16.setText("Tanggal");

        tanggalEdit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(250, 240, 202));
        jLabel17.setText("Ruang");

        ruangEdit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ruangEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "321", "322", "323", "324", "325", "326", "327", "328", "331", "332", "333", "334", "335", "336", "337", "338", "341", "342", "343", "344", "345", "346", "347", "348", "241", "242", "243", "251", "252", "253", "254", "255", "256", "257", "261", "262", "263", "264", "265", "266", "267", "Auditorium", "Basement" }));

        idPmjmEdit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(250, 240, 202));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Id Peminjaman");

        editButton.setBackground(new java.awt.Color(244, 211, 94));
        editButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        editButton.setText("Edit");
        editButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        cariTextField2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cariTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariTextField2KeyReleased(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(244, 211, 94));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        jPanel7.setAlignmentX(0.0F);
        jPanel7.setAlignmentY(0.0F);

        jLabel37.setBackground(new java.awt.Color(255, 0, 153));
        jLabel37.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel37))
        );

        javax.swing.GroupLayout editPeminjamanLayout = new javax.swing.GroupLayout(editPeminjaman);
        editPeminjaman.setLayout(editPeminjamanLayout);
        editPeminjamanLayout.setHorizontalGroup(
            editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPeminjamanLayout.createSequentialGroup()
                .addGroup(editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editPeminjamanLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(editPeminjamanLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(60, 60, 60)
                                    .addComponent(idPmjmEdit))
                                .addGroup(editPeminjamanLayout.createSequentialGroup()
                                    .addGroup(editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17))
                                    .addGap(110, 110, 110)
                                    .addGroup(editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ruangEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tanggalEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(editPeminjamanLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPeminjamanLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(192, 192, 192))
                            .addGroup(editPeminjamanLayout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cariTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editPeminjamanLayout.setVerticalGroup(
            editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPeminjamanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cariTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPmjmEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPeminjamanLayout.createSequentialGroup()
                        .addComponent(tanggalEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ruangEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editPeminjamanLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(editButton)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        layarUtama.add(editPeminjaman, "card4");

        CS.setBackground(new java.awt.Color(13, 59, 102));

        jPanel4.setBackground(new java.awt.Color(250, 240, 202));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel21.setText("Petunjuk Penggunaan");

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel22.setText("masukan, kritik maupun saran");

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel23.setText("kurang jelas");

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jLabel24.setText("Tekan 1 jika ingin menanyakan fitur yang ");

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel25.setText("Tekan 2 jika ingin memberikan ");

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel26.setText("Tekan 3 jika ingin menyudahi pesan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(5, 5, 5)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(250, 240, 202));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 153), new java.awt.Color(51, 0, 0)));
        jPanel3.setToolTipText("");

        jPanel9.setBackground(new java.awt.Color(250, 240, 202));

        cboConnection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client" }));
        cboConnection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboConnectionItemStateChanged(evt);
            }
        });
        cboConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboConnectionActionPerformed(evt);
            }
        });

        txtUsername.setText("Username");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(listMessege);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(cboConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(cboConnection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtMessege.setText("Ada yang bisa saya bantu?");
        txtMessege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessegeActionPerformed(evt);
            }
        });

        btnSend.setText("Kirim");
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendMouseClicked(evt);
            }
        });
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtMessege, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSend))
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMessege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout CSLayout = new javax.swing.GroupLayout(CS);
        CS.setLayout(CSLayout);
        CSLayout.setHorizontalGroup(
            CSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        CSLayout.setVerticalGroup(
            CSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CSLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(CSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CSLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layarUtama.add(CS, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(layarUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addComponent(layarUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        // TODO add your handling code here:

        layarUtama.removeAll();
        layarUtama.repaint();
        layarUtama.revalidate();

        layarUtama.add(home);
        layarUtama.repaint();
        layarUtama.revalidate();
    }//GEN-LAST:event_menuHomeMouseClicked

    private void menuHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseEntered
        // TODO add your handling code here:
        menuHome.setBackground(new Color(13,79,120));
    }//GEN-LAST:event_menuHomeMouseEntered

    private void menuHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseExited
        // TODO add your handling code here:
        menuHome.setBackground(new Color(13,59,102));
    }//GEN-LAST:event_menuHomeMouseExited

    private void menuBuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBuatMouseClicked
        // TODO add your handling code here:
        layarUtama.removeAll();
        layarUtama.repaint();
        layarUtama.revalidate();

        layarUtama.add(buatPeminjaman);
        layarUtama.repaint();
        layarUtama.revalidate();
    }//GEN-LAST:event_menuBuatMouseClicked

    private void menuBuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBuatMouseEntered
        // TODO add your handling code here:
        menuBuat.setBackground(new Color(13,79,120));
    }//GEN-LAST:event_menuBuatMouseEntered

    private void menuBuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBuatMouseExited
        // TODO add your handling code here:
        menuBuat.setBackground(new Color(13,59,102));
    }//GEN-LAST:event_menuBuatMouseExited

    private void menuEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditMouseClicked
        // TODO add your handling code here:
        clearError();

        layarUtama.removeAll();
        layarUtama.repaint();
        layarUtama.revalidate();

        layarUtama.add(editPeminjaman);
        layarUtama.repaint();
        layarUtama.revalidate();
    }//GEN-LAST:event_menuEditMouseClicked

    private void menuEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditMouseEntered
        // TODO add your handling code here:
        menuEdit.setBackground(new Color(13,79,120));
    }//GEN-LAST:event_menuEditMouseEntered

    private void menuEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditMouseExited
        // TODO add your handling code here:
        menuEdit.setBackground(new Color(13,59,102));
    }//GEN-LAST:event_menuEditMouseExited

    private void menuCSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCSMouseClicked
        // TODO add your handling code here:
        layarUtama.removeAll();
        layarUtama.repaint();
        layarUtama.revalidate();

        layarUtama.add(CS);
        layarUtama.repaint();
        layarUtama.revalidate();
    }//GEN-LAST:event_menuCSMouseClicked

    private void menuCSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCSMouseEntered
        // TODO add your handling code here:
        menuCS.setBackground(new Color(13,79,120));
    }//GEN-LAST:event_menuCSMouseEntered

    private void menuCSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCSMouseExited
        // TODO add your handling code here:
        menuCS.setBackground(new Color(13,59,102));
    }//GEN-LAST:event_menuCSMouseExited

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        // TODO add your handling code here:
        menuLogout.setBackground(new Color(13,79,120));
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
        // TODO add your handling code here:
        menuLogout.setBackground(new Color(13,59,102));
    }//GEN-LAST:event_menuLogoutMouseExited

    private void cariTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTextField1KeyReleased
        // TODO add your handling code here:
        String text=cariTextField1.getText();
        DefaultTableModel dtm = (DefaultTableModel) peminjamanTable.getModel();
        if (text.length()==0){
            while(dtm.getRowCount()>0){
                dtm.removeRow(0);
            }
            try {
                //isi tabel
                for(PeminjamanRuang pmjm: Database.getInstance().getListPeminjamanRuangById(idUser)){
                    dtm.addRow(new Object[]{pmjm.getIdPmjm(),pmjm.getPengguna(),pmjm.getKegiatan(),pmjm.getRuang(),pmjm.getTanggal(),pmjm.getStatus()});
                }
            } catch (SQLException ex) {
                System.err.println(ex);
                JOptionPane.showMessageDialog(this, "Gagal mengambil data",
                    "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            //refresh tabel
            while(dtm.getRowCount()>0){
                dtm.removeRow(0);
            }
            try {
                //isi tabel
                for(PeminjamanRuang pmjm: Database.getInstance().getListPencarianById(text,idUser)){
                    dtm.addRow(new Object[]{pmjm.getIdPmjm(),pmjm.getPengguna(),pmjm.getKegiatan(),pmjm.getRuang(),pmjm.getTanggal(),pmjm.getStatus()});
                }
            } catch (SQLException ex) {
                System.err.println(ex);
                JOptionPane.showMessageDialog(this, "Gagal mengambil data",
                    "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cariTextField1KeyReleased

    private void penggunaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penggunaTextFieldActionPerformed

    private void pinjamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamButtonActionPerformed
    // Validasi input
    if (penggunaTextField.getText().isEmpty() || kegiatanTextField.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi");
        return;
    }

    validateKosong();

    // Membuat ID random
    String id = "";
    Random random = new Random();
    for (int i = 0; i < 5; i++) {
        id += random.nextInt(10);
    }

    // Validasi tanggal
    Date input_tgl = tanggalChooser.getDate();
    if (input_tgl == null) {
        errorTanggal.setText("Tanggal Tidak Boleh Kosong");
        return;
    } else {
        errorTanggal.setText("");
    }

    // Format tanggal
    String pattern = "dd MMM yyyy";
    SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
    String tanggal = simpleDateFormat.format(input_tgl);

    // Dapatkan ruang
    String ruang = daftarRuang.getSelectedItem().toString();

    // Membuat objek PeminjamanRuang
    PeminjamanRuang pmjm = new PeminjamanRuang();
    pmjm.setPengguna(penggunaTextField.getText());
    pmjm.setKegiatan(kegiatanTextField.getText());
    pmjm.setTanggal(tanggal);
    pmjm.setRuang(ruang);
    pmjm.setIdPmjm(id);
    pmjm.setStatus("memverifikasi");

    // Operasi database
    try {
        if (Database.getInstance().pengecekanRuang(tanggal, ruang)) {
            JOptionPane.showMessageDialog(this, "Ruang sudah digunakan");
        } else if (!validateTanggal()) {
            JOptionPane.showMessageDialog(this, "Peminjaman Dapat Dilakukan Seminggu Sebelum Kegiatan");
        } else {
            Database.getInstance().insertPeminjaman(pmjm, idUser);
            JOptionPane.showMessageDialog(this, "Berhasil Meminjam Ruang");
            clearForm();
            new DashbordUser(idUser).setVisible(true);
            this.dispose();
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Gagal Meminjam Ruang: " + ex.getMessage());
        ex.printStackTrace(); // Print stack trace untuk debugging
    }
    }//GEN-LAST:event_pinjamButtonActionPerformed

    private void editTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) editTable.getModel();
        String idPmjm = dtm.getValueAt(editTable.getSelectedRow(), 0).toString();
        String tglPmjm = dtm.getValueAt(editTable.getSelectedRow(), 4).toString();
        String ruangPmjm = dtm.getValueAt(editTable.getSelectedRow(), 3).toString();
        idPmjmEdit.setText(idPmjm);
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMM yyyy");
            Date waktu = dateFormat.parse(tglPmjm);
            tanggalEdit.setDate(waktu);
        } catch (ParseException e) {
            // Tangani kesalahan saat parsing tanggal
            JOptionPane.showMessageDialog(this, "Gagal mengambil tanggal",
                "Gagal", JOptionPane.ERROR_MESSAGE);
        }
        ruangEdit.setSelectedItem(ruangPmjm);
    }//GEN-LAST:event_editTableMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        String idPmjm=idPmjmEdit.getText();
        String ruang=ruangEdit.getSelectedItem().toString();
        Date tanggal=tanggalEdit.getDate();
        if(idPmjm.isEmpty()){
            JOptionPane.showMessageDialog(this, "Id Tidak Boleh Kosong");
            idPmjmEdit.requestFocus();
        }
        else if(tanggal==null){
            JOptionPane.showMessageDialog(this, "Tanggal Tidak Boleh Kosong");
            tanggalEdit.requestFocus();
        }
        else if(ruang.equals("-")){
            JOptionPane.showMessageDialog(this, "Ruang Tidak Boleh Kosong");
            ruangEdit.requestFocus();
        }
        else{
            try{
                String pattern = "dd MMM yyyy";
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
                String tgl = simpleDateFormat.format(tanggal);
                Database.getInstance().editPeminjaman(idPmjm, tgl, ruang,"memverifikasi");
                JOptionPane.showMessageDialog(this, "Berhasil Mengedit Peminjaman Ruang");
                loadTableData();
                idPmjmEdit.setText("");
                ruangEdit.setSelectedIndex(0);
                tanggalEdit.setDate(null);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Gagal Mengedit Peminjaman Ruang");
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void cariTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTextField2KeyReleased
        // TODO add your handling code here:
        String text=cariTextField2.getText();
        DefaultTableModel dtm = (DefaultTableModel) editTable.getModel();
        if (text.length()==0){
            while(dtm.getRowCount()>0){
                dtm.removeRow(0);
            }
            try {
                //isi tabel
                for(PeminjamanRuang pmjm: Database.getInstance().getListPeminjamanRuangById(idUser)){
                    dtm.addRow(new Object[]{pmjm.getIdPmjm(),pmjm.getPengguna(),pmjm.getKegiatan(),pmjm.getRuang(),pmjm.getTanggal(),pmjm.getStatus()});
                }
            } catch (SQLException ex) {
                System.err.println(ex);
                JOptionPane.showMessageDialog(this, "Gagal mengambil data",
                    "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            //refresh tabel
            while(dtm.getRowCount()>0){
                dtm.removeRow(0);
            }
            try {
                //isi tabel
                for(PeminjamanRuang pmjm: Database.getInstance().getListPencarianById(text,idUser)){
                    dtm.addRow(new Object[]{pmjm.getIdPmjm(),pmjm.getPengguna(),pmjm.getKegiatan(),pmjm.getRuang(),pmjm.getTanggal(),pmjm.getStatus()});
                }
            } catch (SQLException ex) {
                System.err.println(ex);
                JOptionPane.showMessageDialog(this, "Gagal mengambil data",
                    "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cariTextField2KeyReleased

    private ClientController clientController;
    private ServerController serverController;
    private JTextArea txtChatArea;
    private JTextField txtMessageField;
    private ChatClient chatClient;
    
    private void displayMessage(String message) {
        SwingUtilities.invokeLater(() -> {
            txtChatArea.append(message + "\n");
        });
    }
  
    private void cboConnectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboConnectionItemStateChanged

    }//GEN-LAST:event_cboConnectionItemStateChanged

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed

    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtMessegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessegeActionPerformed
        if (txtMessageField != null) {
        String message = txtMessageField.getText().trim();
        displayMessage("You: " + message);
        String response = chatClient.sendMessage(message);
        displayMessage("Server: " + response);
        txtMessageField.setText("");
    }
    }//GEN-LAST:event_txtMessegeActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        String message = txtMessageField.getText().trim();
        displayMessage("You: " + message);
        String response = clientController.sendMessage(message);
        displayMessage("Server: " + response);
        txtMessageField.setText("");
    }//GEN-LAST:event_btnSendActionPerformed

    private void cboConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboConnectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboConnectionActionPerformed

    private void btnSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendMouseClicked

    public boolean validateTanggal(){
        Date input_tgl = tanggalChooser.getDate();
        String pattern = "dd MM yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        String input = simpleDateFormat.format(input_tgl);
        String sI = input.substring(0, 2);
        String sI1 = input.substring(3, 5);
        String sI2 = input.substring(6, 10);
        int tglI = Integer.valueOf(sI);
        int blnI = Integer.valueOf(sI1);
        int thnI = Integer.valueOf(sI2);
        
        LocalDateTime tglSekarang = LocalDateTime.now(); 
        LocalDateTime tglValidasi = tglSekarang.plusDays(7);
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd MM yyyy");  
        String formattedDate = tglValidasi.format(myFormatObj); 
        String sV = formattedDate.substring(0, 2);
        String sV1 = formattedDate.substring(3, 5);
        String sV2 = formattedDate.substring(6, 10);
        int tglV = Integer.valueOf(sV);
        int blnV = Integer.valueOf(sV1);
        int thnV = Integer.valueOf(sV2);
        
        if(tglI<tglV) {
            if(blnI<=blnV)
                if(thnI<=thnV)
                    return true;            
            return false;
        } else {
            if(blnI<blnV){
                if(thnI<=thnV)
                    return true;
                return false;
            }else{
                if(thnI<thnV)
                    return true;
                return false;
            }         
        }
    }
    
    private void clearForm() {
        penggunaTextField.setText("");
        kegiatanTextField.setText("");
        tanggalChooser.setDateFormatString("");
        daftarRuang.setSelectedIndex(0);
    }
    
    private void clearError() {
        errorPengguna.setText("");
        errorKegiatan.setText("");
        errorTanggal.setText("");
        errorRuang.setText("");
    }
    
    public void validateKosong() {
        if (penggunaTextField.getText().equals("")) {
            errorPengguna.setText("Pengguna Tidak Boleh Kosong");
        }
        if (kegiatanTextField.getText().equals("")) {
            errorKegiatan.setText("Kegiatan Tidak Boleh Kosong");
        }
        Date date;
        date = tanggalChooser.getDate();
        if (date==null) {
            errorTanggal.setText("Tanggal Tidak Boleh Kosong");
        }
        if (daftarRuang.getSelectedItem().toString().equals("-")) {
            errorRuang.setText("Pilih Ruangan");
        }
    }
    
    private void loadTableData(){
        DefaultTableModel dtm1 = (DefaultTableModel) peminjamanTable.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel) editTable.getModel();
        //refresh tabel
        while(dtm1.getRowCount()>0){
            dtm1.removeRow(0);
            dtm2.removeRow(0);
        }
        try {
        //isi tabel
            for(PeminjamanRuang pmjm: Database.getInstance().getListPeminjamanRuang()){
                dtm1.addRow(new Object[]{pmjm.getIdPmjm(),pmjm.getPengguna(),pmjm.getKegiatan(),pmjm.getRuang(),
                    pmjm.getTanggal(),pmjm.getStatus()});
                dtm2.addRow(new Object[]{pmjm.getIdPmjm(),pmjm.getPengguna(),pmjm.getKegiatan(),pmjm.getRuang(),
                    pmjm.getTanggal(),pmjm.getStatus()});
            }
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data", 
                    "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public final void tampil_ruang() {
        try {
            ArrayList<String> ruang = (ArrayList<String>) Database.getInstance().getListRuang();
            int n = ruang.size();
            for (int i = 0; i < n; i++) {
                daftarRuang.addItem(ruang.get(i));
                ruangEdit.addItem(ruang.get(i));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data", 
                    "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CS;
    private javax.swing.JButton btnSend;
    private javax.swing.JPanel buatPeminjaman;
    private javax.swing.JTextField cariTextField1;
    private javax.swing.JTextField cariTextField2;
    private javax.swing.JComboBox<String> cboConnection;
    private javax.swing.JComboBox<String> daftarRuang;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel editPeminjaman;
    private javax.swing.JTable editTable;
    private javax.swing.JLabel errorKegiatan;
    private javax.swing.JLabel errorPengguna;
    private javax.swing.JLabel errorRuang;
    private javax.swing.JLabel errorTanggal;
    private javax.swing.JPanel home;
    private javax.swing.JTextField idPmjmEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kegiatanTextField;
    private javax.swing.JPanel layarUtama;
    private javax.swing.JList<String> listMessege;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuBuat;
    private javax.swing.JPanel menuCS;
    private javax.swing.JPanel menuEdit;
    private javax.swing.JPanel menuHome;
    private javax.swing.JPanel menuLogout;
    private javax.swing.JTable peminjamanTable;
    private javax.swing.JTextField penggunaTextField;
    private javax.swing.JButton pinjamButton;
    private javax.swing.JComboBox<String> ruangEdit;
    private com.toedter.calendar.JDateChooser tanggalChooser;
    private com.toedter.calendar.JDateChooser tanggalEdit;
    private javax.swing.JTextField txtMessege;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
